### ISSUE TITLE
Game activated but functions not working

### ISSUE THREAD

**Issue by ParticalPlusing** [stereolabs/zed-UE5#10]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I followed the Stereolabs ZED - UE5 Examples to setup environment many times.
No error shows but it seems not activate AI function like body tracking or spatial mapping...

### Steps to Reproduce

1. Download and install the latest ZED SDK. (3.8.2)
2. Download and install Stereolabs ZED - UE5 Examples (v1.1)
3. In your project root directory right click on the YourProjectName.uproject file and select Generate Visual Studio project files in the context menu.
4. Open Visual Studio and compile. Launch the project from the uproject file or Visual Studio.
5. Trying any Levels inside Unreal projects.

### Expected Result

Expected shows what the video present in the Github README. 
Like BP_Manny will follow your pose, spatial mapping will show the mesh.

### Actual Result

Only showing the camera view.

### ZED Camera model

ZED2i

### Environment

```shell
OS: Windows 10 Pro
CPU: Intel i5-10400
GPU: Nvidia RTX-3060
ZED SDK version: 3.8.2
Unreal version: 5.1
```

**Comment by SLJLMacarit** [comment]
Hello and thanks for reaching us!

When trying to run the levels, do you get this message in the console?
`AI model : [the model] is not downloaded/optimized, please optimize it using the ZED Diagnostic tool (use the *-h* option to have all the informations needed 

The Object Detection/Body Tracking modules use AI models that need to be optimized before their first use. The UE5 plugin does not do this them by itself, so we advise you to optimize them externally using the **ZED Diagnostic** tool located in the ZED SDK installation folder (usually Program Files (x86)/ZED SDK/tools).

The process is described here: [How can I optimize the ZED SDK AI models manually?](https://support.stereolabs.com/hc/en-us/articles/9747407795223-How-can-I-optimize-the-ZED-SDK-AI-models-manually-)

You will only need to do this procedure once.

Best regards,
Jean-Loup Macarit

**Comment by ParticalPlusing** [comment]
Thank you for the answering!
**It finally works!**

For someone who probably met same trouble:
1. 
Followed the steps in this [How can I optimize the ZED SDK AI models manually?](https://support.stereolabs.com/hc/en-us/articles/9747407795223-How-can-I-optimize-the-ZED-SDK-AI-models-manually-).

2.
Check "ZED Diagnostic" AI Models should be a green tick as well. If not, probably you need to optimize AI models again.
Do this in cmd again. (Optimized all the download AI models)
`“ZED Diagnostic.exe” -aio`

3.
And when you run your application with the NEURAL depth mode, probably be frozen sometimes.
I found another post about it: [Why is my application frozen when using the NEURAL depth mode?](https://support.stereolabs.com/hc/en-us/articles/4852371065623-Why-is-my-application-frozen-when-using-the-NEURAL-depth-mode-)
Also, just wait a few seconds (or minutes), everything should work fine.



Again, thanks you for answering.

Thanks and Best Regards,
Partical
