### ISSUE TITLE
Can't open v1.3 in UE 5.2

### ISSUE THREAD

**Issue by maxwaba** [stereolabs/zed-UE5#23]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Can't open project in UE 5.2

### Steps to Reproduce

1.Download
2.Switch engine version
3.Build solution
...

### Expected Result

Open ZED demo UE project

### Actual Result

The following error message: 

The following modules are missing or built with a different engine version:

  ZEDSamples
  Stereolabs
  ZED
  SpatialMapping
  SpatialMappingEditor
  ZEDEditor
  EnvironmentalLighting

Would you like to rebuild them now?

(rebuild fails)

### ZED Camera model

ZED2i

### Environment

```shell
Win 11
UE 5.2
```

**Comment by sdetwiler** [comment]
I recently had a similar problem getting the modules to build on Windows 10 with UE 5.1. Attempting to build the .sln manually with Visual Studio 2022 led me to discover that StereolabsBuild.cs:26 is looking for the CUDA installation through the environment variable `CUDA_PATH` but the CUDA v12.1 installation set the environment variable  `CUDA_PATH_V12_1`. Setting the System environment variable `CUDA_PATH` to the same value that was set for `CUDA_PATH_V12_1` allowed me to successfully build the modules. This approach may solve your problem.

**Comment by SLJLMacarit** [comment]
Hi @maxwaba, 
The plugin is compatible only with UE5.1 for now, we'll be porting it to UE5.2 in the near future.
Do you have any error along with the failing rebuild? As @sdetwiler pointed out, what version of CUDA are you using?

@sdetwiler thanks for pointing this out, we'll fix this shortly.

Jean-Loup

**Comment by samphilips** [comment]
> the environment variable `CUDA_PATH`
where do we find this file StereolabsBuild.cs  to change the CUDA_PATH for required version, the error I am getting right now is as follows, 
![image](https://github.com/stereolabs/zed-UE5/assets/139512584/7afd6d21-24a8-4d7f-a0c1-1fe498a43c1f)
![image](https://github.com/stereolabs/zed-UE5/assets/139512584/9fd089fa-1724-4913-8cac-a579f7103423)

**Comment by SLJLMacarit** [comment]
The file itself should not be the issue, but it is located here (trace back from your pulled repo): https://github.com/stereolabs/zed-UE5/blob/main/Plugins/Stereolabs/Source/Stereolabs/Stereolabs.Build.cs

Please check that the environment variable "CUDA_PATH"'s value is set to your CUDA 12.1 install, and if that is not the case, edit it to the path you need, restart your computer, and try again.

**Comment by samphilips** [comment]
I am getting the same error after changing the path environment 
![image](https://github.com/stereolabs/zed-UE5/assets/139512584/cd369407-a131-4b8a-b73d-36f70425e850)
![image](https://github.com/stereolabs/zed-UE5/assets/139512584/e3822492-f0fa-4824-8d25-733601c39d62)
I am using windows 11pro at the moment, would that be a problem ?
