### ISSUE TITLE
Unable to launch on Windows 11

### ISSUE THREAD

**Issue by bardiaHSZD** [stereolabs/zed-UE5#31]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

Here is the error I encountered when I did Start without Debugging (Ctrl+F5) on Visual Studio 2022 on two separate machines:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "...\Engine\Build\BatchFiles\Build.bat" ZEDSamplesEditor Win64 Development -Project="...\Downloads\\zed-UE5-1.6_UE5.2\zed-UE5-1.6_UE5.2\ZEDSamples.uproject" -WaitMutex -FromMsBuild" exited with code 6.	ZEDSamples	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	44	

### Steps to Reproduce

1. I downloaded ZED SDK 4.0.6 for CUDA 12 (Win 10/11)
2. I downloaded ZED-UE5 and opened the project with UE. 
3. It prompted for rebuild. 
4. I rebuilt the solution using VS 2022, 46 were successful and 1 was skipped, with no errors.
5. When I wanted to Start Without Debugging I got the error mentioned in the description 
...

### Expected Result

Opening the unreal plugin successfully with no errors

### Actual Result

Unable to open the ZED-UE5 project.

### ZED Camera model

ZED2i

### Environment

```shell
System 1:
OS: Windows 11
CPU: AMD Ryzen 5000 Series 9
GPU: RTX 3050 TI Laptop
ZED SDK: 4.0.6
Camera: Zed 2i

System 2:
OS: Windows 11
CPU: Intel Core i9
GPU: RTX 3080
ZED SDK: 4.0.6
Camera Zed 2i
```

### Anything else?

None

**Comment by SLJLMacarit** [comment]
Hello,

Sorry for the delay, we'll take a look at this shortly.
Were you able to run it since reporting the issue?
