### ISSUE TITLE
Unreal Engine 5.4 plugin support

### ISSUE THREAD

**Issue by KenTYLeung** [stereolabs/zed-UE5#41]
Hi,

I bought a ZED 2i camera.  I was trying to use the zed-UE5 plugin in my project running in Unreal Engine 5.4.  The project build successfully but when I tried to open the project, there was an error.

![image (4)](https://github.com/stereolabs/zed-UE5/assets/48813599/9d92800a-9842-4d96-93c9-c1c6480b235a)
![image (5)](https://github.com/stereolabs/zed-UE5/assets/48813599/ed25e5fc-faff-4b25-89d1-be2d8531cc10)

May I know when is there a ZED plugin that support Unreal Engine 5.4?  Or is there any way to get around this problem so I can continue with Unreal Engine 5.4?

Please advise, thanks.

Ken

**Comment by troto-maton** [comment]
Hi Stereolabs,

I've been a dev working with a pair of ZED2i's in UE5 and while we were previously working in UE5.3, our most recent projects have been using UE5.4. I am also wondering how long it may be until support for UE5.4 is released. 

Alternatively, if there is a known, stable workaround, that would work for the time being as well. Thanks!

Tristan

**Comment by SLJLMacarit** [comment]
Hey there @troto-maton 
You can try the [5.4 branch](https://github.com/stereolabs/zed-UE5/tree/unreal_5.4) now!
Don't hesite to report any issues you find, either here or on this forum post for more visibility: https://community.stereolabs.com/t/zed-plugin-for-unreal-engine-5-4-support/6534/7

This issue will be closed once we're sure it works but KenTYLeung above has issues we're investigating.

**Comment by troto-maton** [comment]
Thanks for the rapid response, @SLJLMacarit! 

On a partially related note, I'm trying to set up the project with the ZEDLiveLink plugin, but it refuses to build when I add the plugin to my folder structure of the UE5.4 project (this process was pretty seamless previously). Do you happen know if the 5.4 version is compatible with the current iteration of the ZEDLiveLink plugin? Thanks!

Tristan
