### ISSUE TITLE
Compile failure due to ZED SDK version mismatch

### ISSUE THREAD

**Issue by james-yoo** [stereolabs/zed-UE5#44]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

zed-UE5 plugins 

### Steps to Reproduce

1. Download source code(branch: master) or released [plugin](https://github.com/stereolabs/zed-UE5/releases/tag/v4.2.0)
2. Compile project using Visual Studio 2022

### Expected Result

ZED plugins are compiled without error.

### Actual Result

Compile failed with following message:  
'ZED SDK Minor Version mismatch'

### ZED Camera model

ZED2

### Environment

```shell
OS: Windows 11
CPU: Intel i9 12900K
GPU: RTX 3070 Ti
UE5: 5.4.4
ZED SDK: 4.2.0
```

### Anything else?

Following line should be fixed to '2' for ZED SDK 4.2.0
https://github.com/stereolabs/zed-UE5/blob/b9b368beca4528da47f7097cafa4ac3fdc14f93e/Plugins/Stereolabs/Source/Stereolabs/Stereolabs.Build.cs#L104

**Comment by Bvallon-sl** [comment]
Hi,

Thanks for the report.
I indeed made a mistake when pushing the patch for the 4.2 support.

I just pushed a fix on main, could you try it and tell me if it's fixed for you as well?
I'll update the release just after.

Best,

**Comment by james-yoo** [comment]
@Bvallon-sl,
Thanks for your fast support. It works!

**Comment by Bvallon-sl** [comment]
Glad to hear, I'm closing the issue.
