### ISSUE TITLE
I want to use it in ubuntu

### ISSUE THREAD

**Issue by qingyuyijiu** [stereolabs/zed-UE5#46]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Because I use UE5 in ubuntu 20.04,but can't use zed2 plugin. I hope ZED2 plugin could be used in ubuntu.

**Comment by Bvallon-sl** [comment]
Hi,

There is no plan to add Ubuntu support for the moment.
