### ISSUE TITLE
I can't find the Point Cloud Depth View level for unreal in the plugin

### ISSUE THREAD

**Issue by Mjemerico** [stereolabs/zed-UE5#7]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

The level for Point Cloud Depth View is missing from the unreal 5.0 plugin.

### Steps to Reproduce

1. Checked the levels folder in zed unreal 5.0 plugin, but couldn't find the Point Cloud Depth View level others were present

### Expected Result

Expected to find the Point Cloud Depth View level files in the zed unreal 5.0 plugin folder

### Actual Result

Point Cloud Depth View files is missing in the zed unreal plugin level folder

### ZED Camera model

ZED2

### Environment

```shell
Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.70 GHz
Installed RAM	16.0 GB (15.7 GB usable)
Windows 11 Pro
```

**Comment by Bvallon-sl** [comment]
Hi,

Indeed, the Map is not visible when using UE5.0.3 but is available with UE5.1.

I'll investigate this and I come back to you when it's fixed.

Best, regards.

**Comment by Bvallon-sl** [comment]
Hi,

It should be fixed now.
However, from now on, we strongly suggest to use UE5.1 as it will be the version we will use to work on the plugin.

Best,
Benjamin Vallon

**Comment by Mjemerico** [comment]
Thanks for the fix
